# Generated by Django 2.1.5 on 2019-04-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('message_level', models.PositiveIntegerField()),
                ('method', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('raw_uri', models.TextField()),
                ('url_name', models.CharField(max_length=255)),
                ('func_name', models.CharField(max_length=255)),
                ('remote_addr', models.CharField(blank=True, max_length=255)),
                ('forwarded_for', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('client_agent', models.CharField(blank=True, max_length=255)),
                ('client_version', models.CharField(blank=True, max_length=255)),
                ('user', models.CharField(blank=True, max_length=255)),
                ('tablet_id', models.PositiveIntegerField()),
                ('kwargs', models.TextField(blank=True)),
                ('args', models.TextField(blank=True)),
                ('extra', models.TextField(blank=True)),
                ('api_version', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'api_log',
                'ordering': ['date', 'time', 'id'],
            },
        ),
    ]
