# Generated by Django 2.1.5 on 2019-06-01 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apilog',
            options={'ordering': ['-date', '-time', '-id']},
        ),
    ]
