# Generated by Django 2.1.5 on 2019-06-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0003_api_context_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCommandType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('command', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'api_command_types',
                'ordering': ['name'],
            },
        ),
    ]
