# Generated by Django 2.1.5 on 2019-06-06 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0005_api_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicommandtype',
            name='command',
            field=models.TextField(),
        ),
    ]
