# Generated by Django 2.1.5 on 2019-06-09 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0006_api_command_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicommand',
            name='uses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
