# Generated by Django 2.1.5 on 2019-06-09 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0007_api_command_uses'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicommand',
            name='command',
            field=models.TextField(blank=True),
        ),
    ]
