# Generated by Django 2.2.2 on 2019-06-29 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0008_api_command_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicommand',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
