# Generated by Django 2.2.5 on 2019-09-03 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jsonapi', '0009_apicommand_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apicommand',
            options={'ordering': ['id'], 'verbose_name': 'Api command', 'verbose_name_plural': 'Api commands'},
        ),
        migrations.AlterModelOptions(
            name='apicommandtype',
            options={'ordering': ['name'], 'verbose_name': 'Api command type', 'verbose_name_plural': 'Api command types'},
        ),
        migrations.AlterModelOptions(
            name='apicontexttype',
            options={'ordering': ['name'], 'verbose_name': 'Api context type', 'verbose_name_plural': 'Api context types'},
        ),
        migrations.AlterModelOptions(
            name='apilog',
            options={'ordering': ['-date', '-time', '-id'], 'verbose_name': 'Api log', 'verbose_name_plural': 'Api logs'},
        ),
        migrations.AlterField(
            model_name='apicommand',
            name='command',
            field=models.TextField(blank=True, verbose_name='command'),
        ),
        migrations.AlterField(
            model_name='apicommand',
            name='command_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jsonapi.ApiCommandType', verbose_name='command type'),
        ),
        migrations.AlterField(
            model_name='apicommand',
            name='context_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jsonapi.ApiContextType', verbose_name='context type'),
        ),
        migrations.AlterField(
            model_name='apicommand',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='apicommand',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='apicommand',
            name='ending',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='ending'),
        ),
        migrations.AlterField(
            model_name='apicommand',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='apicommand',
            name='starting',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='starting'),
        ),
        migrations.AlterField(
            model_name='apicommand',
            name='tablets',
            field=models.ManyToManyField(blank=True, to='work.Tablet', verbose_name='tablets'),
        ),
        migrations.AlterField(
            model_name='apicommand',
            name='uses',
            field=models.PositiveIntegerField(default=0, verbose_name='uses'),
        ),
        migrations.AlterField(
            model_name='apicommandtype',
            name='command',
            field=models.TextField(verbose_name='command'),
        ),
        migrations.AlterField(
            model_name='apicommandtype',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='apicommandtype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='apicontexttype',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='apicontexttype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='api_version',
            field=models.PositiveIntegerField(verbose_name='api version'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='args',
            field=models.TextField(blank=True, verbose_name='arguments'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='client_agent',
            field=models.CharField(blank=True, max_length=255, verbose_name='client agent'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='client_version',
            field=models.CharField(blank=True, max_length=255, verbose_name='client version'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='extra',
            field=models.TextField(blank=True, verbose_name='extra'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='forwarded_for',
            field=models.CharField(blank=True, max_length=255, verbose_name='forwarded for'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='func_name',
            field=models.CharField(max_length=255, verbose_name='function name'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='kwargs',
            field=models.TextField(blank=True, verbose_name='keyword arguments'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='message_level',
            field=models.PositiveIntegerField(verbose_name='message level'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='method',
            field=models.CharField(max_length=255, verbose_name='metod'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='path',
            field=models.CharField(max_length=255, verbose_name='path'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='raw_uri',
            field=models.TextField(verbose_name='raw uri'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='remote_addr',
            field=models.CharField(blank=True, max_length=255, verbose_name='remote address'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='tablet_id',
            field=models.PositiveIntegerField(verbose_name='tablet id'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='time',
            field=models.TimeField(verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='url_name',
            field=models.CharField(max_length=255, verbose_name='url name'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='user',
            field=models.CharField(blank=True, max_length=255, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, verbose_name='user agent'),
        ),
    ]
