# Generated by Django 2.1.3 on 2018-11-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSection',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('header_title', models.CharField(blank=True, max_length=255)),
                ('header_order', models.IntegerField()),
                ('home_title', models.CharField(blank=True, max_length=255)),
                ('home_order', models.IntegerField()),
                ('home_image', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'website_home_sections',
                'ordering': ['name'],
            },
        ),
    ]
