# Generated by Django 2.1.3 on 2018-11-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_home_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homesection',
            options={'ordering': ['home_order']},
        ),
    ]
