# Generated by Django 2.1.4 on 2018-12-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesection',
            name='admin_login_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='homesection',
            name='login_required',
            field=models.BooleanField(default=False),
        ),
    ]
