# Generated by Django 2.1.5 on 2019-02-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0025_equipment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminListDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('ActivityAdmin', 'ActivityAdmin'), ('ActivityInLinesAdmin', 'ActivityInLinesAdmin'), ('ActivityRoomAdmin', 'ActivityRoomAdmin'), ('BedTypeAdmin', 'BedTypeAdmin'), ('BrandAdmin', 'BrandAdmin'), ('BuildingAdmin', 'BuildingAdmin'), ('CompanyAdmin', 'CompanyAdmin'), ('ContinentAdmin', 'ContinentAdmin'), ('ContractAdmin', 'ContractAdmin'), ('ContractTypeAdmin', 'ContractTypeAdmin'), ('CountryAdmin', 'CountryAdmin'), ('EmployeeAdmin', 'EmployeeAdmin'), ('EquipmentAdmin', 'EquipmentAdmin'), ('EquipmentTypeAdmin', 'EquipmentTypeAdmin'), ('JobTypeAdmin', 'JobTypeAdmin'), ('LanguageAdmin', 'LanguageAdmin'), ('LocationAdmin', 'LocationAdmin'), ('LoginAdmin', 'LoginAdmin'), ('PositionAdmin', 'PositionAdmin'), ('RegionAdmin', 'RegionAdmin'), ('RegionAliasAdmin', 'RegionAliasAdmin'), ('RoomAdmin', 'RoomAdmin'), ('RoomTypeAdmin', 'RoomTypeAdmin'), ('ServiceAdmin', 'ServiceAdmin'), ('ServiceExtraAdmin', 'ServiceExtraAdmin'), ('StructureAdmin', 'StructureAdmin'), ('TabletAdmin', 'TabletAdmin'), ('TimestampAdmin', 'TimestampAdmin'), ('TimestampDirectionAdmin', 'TimestampDirectionAdmin')], max_length=255)),
                ('field', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'website_admin_list_display',
                'ordering': ['model', 'order', 'field'],
            },
        ),
        migrations.AlterField(
            model_name='adminsearchable',
            name='model',
            field=models.CharField(choices=[('ActivityAdmin', 'ActivityAdmin'), ('ActivityInLinesAdmin', 'ActivityInLinesAdmin'), ('ActivityRoomAdmin', 'ActivityRoomAdmin'), ('AdminListDisplayAdmin', 'AdminListDisplayAdmin'), ('BedTypeAdmin', 'BedTypeAdmin'), ('BrandAdmin', 'BrandAdmin'), ('BuildingAdmin', 'BuildingAdmin'), ('CompanyAdmin', 'CompanyAdmin'), ('ContinentAdmin', 'ContinentAdmin'), ('ContractAdmin', 'ContractAdmin'), ('ContractTypeAdmin', 'ContractTypeAdmin'), ('CountryAdmin', 'CountryAdmin'), ('EmployeeAdmin', 'EmployeeAdmin'), ('EquipmentAdmin', 'EquipmentAdmin'), ('EquipmentTypeAdmin', 'EquipmentTypeAdmin'), ('JobTypeAdmin', 'JobTypeAdmin'), ('LanguageAdmin', 'LanguageAdmin'), ('LocationAdmin', 'LocationAdmin'), ('LoginAdmin', 'LoginAdmin'), ('PositionAdmin', 'PositionAdmin'), ('RegionAdmin', 'RegionAdmin'), ('RegionAliasAdmin', 'RegionAliasAdmin'), ('RoomAdmin', 'RoomAdmin'), ('RoomTypeAdmin', 'RoomTypeAdmin'), ('ServiceAdmin', 'ServiceAdmin'), ('ServiceExtraAdmin', 'ServiceExtraAdmin'), ('StructureAdmin', 'StructureAdmin'), ('TabletAdmin', 'TabletAdmin'), ('TimestampAdmin', 'TimestampAdmin'), ('TimestampDirectionAdmin', 'TimestampDirectionAdmin')], max_length=255),
        ),
        migrations.AlterField(
            model_name='adminsearchable',
            name='ref_model',
            field=models.CharField(choices=[('ActivityAdmin', 'ActivityAdmin'), ('ActivityInLinesAdmin', 'ActivityInLinesAdmin'), ('ActivityRoomAdmin', 'ActivityRoomAdmin'), ('AdminListDisplayAdmin', 'AdminListDisplayAdmin'), ('BedTypeAdmin', 'BedTypeAdmin'), ('BrandAdmin', 'BrandAdmin'), ('BuildingAdmin', 'BuildingAdmin'), ('CompanyAdmin', 'CompanyAdmin'), ('ContinentAdmin', 'ContinentAdmin'), ('ContractAdmin', 'ContractAdmin'), ('ContractTypeAdmin', 'ContractTypeAdmin'), ('CountryAdmin', 'CountryAdmin'), ('EmployeeAdmin', 'EmployeeAdmin'), ('EquipmentAdmin', 'EquipmentAdmin'), ('EquipmentTypeAdmin', 'EquipmentTypeAdmin'), ('JobTypeAdmin', 'JobTypeAdmin'), ('LanguageAdmin', 'LanguageAdmin'), ('LocationAdmin', 'LocationAdmin'), ('LoginAdmin', 'LoginAdmin'), ('PositionAdmin', 'PositionAdmin'), ('RegionAdmin', 'RegionAdmin'), ('RegionAliasAdmin', 'RegionAliasAdmin'), ('RoomAdmin', 'RoomAdmin'), ('RoomTypeAdmin', 'RoomTypeAdmin'), ('ServiceAdmin', 'ServiceAdmin'), ('ServiceExtraAdmin', 'ServiceExtraAdmin'), ('StructureAdmin', 'StructureAdmin'), ('TabletAdmin', 'TabletAdmin'), ('TimestampAdmin', 'TimestampAdmin'), ('TimestampDirectionAdmin', 'TimestampDirectionAdmin')], max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='adminlistdisplay',
            unique_together={('model', 'order'), ('model', 'field')},
        ),
    ]
