# Generated by Django 2.2.2 on 2019-06-23 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_admin_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminoption',
            name='group',
            field=models.CharField(default='main', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='adminoption',
            unique_together={('section', 'group', 'name')},
        ),
    ]
