# Generated by Django 2.2.2 on 2019-06-23 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0039_admin_option_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminoption',
            options={'ordering': ['section', 'group', 'name']},
        ),
    ]
