# Generated by Django 2.2.5 on 2019-09-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0042_delete_adminsection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminexportcsvmap',
            options={'ordering': ['model', 'order', 'title', 'field'], 'verbose_name': 'Admin Export CSV Map', 'verbose_name_plural': 'Admin Export CSV Maps'},
        ),
        migrations.AlterModelOptions(
            name='adminlistdisplay',
            options={'ordering': ['model', 'order', 'field'], 'verbose_name': 'Admin List Display', 'verbose_name_plural': 'Admin List Display'},
        ),
        migrations.AlterModelOptions(
            name='adminlistdisplaylink',
            options={'ordering': ['model', 'order', 'field'], 'verbose_name': 'Admin List Display Link', 'verbose_name_plural': 'Admin List Display Links'},
        ),
        migrations.AlterModelOptions(
            name='adminlistfilter',
            options={'ordering': ['model', 'order', 'field'], 'verbose_name': 'Admin List Filter', 'verbose_name_plural': 'Admin List Filters'},
        ),
        migrations.AlterModelOptions(
            name='adminoption',
            options={'ordering': ['section', 'group', 'name'], 'verbose_name': 'Admin Option', 'verbose_name_plural': 'Admin Options'},
        ),
        migrations.AlterModelOptions(
            name='adminsearchable',
            options={'ordering': ['model', 'field'], 'verbose_name': 'Admin Searchable', 'verbose_name_plural': 'Admin Searchables'},
        ),
        migrations.AlterModelOptions(
            name='homesection',
            options={'ordering': ['header_order'], 'verbose_name': 'Home Section', 'verbose_name_plural': 'Home Sections'},
        ),
        migrations.AlterField(
            model_name='adminexportcsvmap',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='adminexportcsvmap',
            name='field',
            field=models.CharField(max_length=255, verbose_name='field'),
        ),
        migrations.AlterField(
            model_name='adminexportcsvmap',
            name='model',
            field=models.CharField(choices=[('ActivityAdmin', 'ActivityAdmin'), ('ActivityInLinesAdmin', 'ActivityInLinesAdmin'), ('ActivityRoomAdmin', 'ActivityRoomAdmin'), ('AdminExportCSVMapAdmin', 'AdminExportCSVMapAdmin'), ('AdminListDisplayAdmin', 'AdminListDisplayAdmin'), ('AdminListDisplayLinkAdmin', 'AdminListDisplayLinkAdmin'), ('AdminListFilterAdmin', 'AdminListFilterAdmin'), ('AdminOptionAdmin', 'AdminOptionAdmin'), ('AdminSearchableAdmin', 'AdminSearchableAdmin'), ('ApiCommandAdmin', 'ApiCommandAdmin'), ('ApiCommandTypeAdmin', 'ApiCommandTypeAdmin'), ('ApiContextTypeAdmin', 'ApiContextTypeAdmin'), ('ApiLogAdmin', 'ApiLogAdmin'), ('BedTypeAdmin', 'BedTypeAdmin'), ('BrandAdmin', 'BrandAdmin'), ('BuildingAdmin', 'BuildingAdmin'), ('CompanyAdmin', 'CompanyAdmin'), ('ContinentAdmin', 'ContinentAdmin'), ('ContractAdmin', 'ContractAdmin'), ('ContractTypeAdmin', 'ContractTypeAdmin'), ('CountryAdmin', 'CountryAdmin'), ('EmployeeAdmin', 'EmployeeAdmin'), ('EquipmentAdmin', 'EquipmentAdmin'), ('EquipmentTypeAdmin', 'EquipmentTypeAdmin'), ('HomeSectionAdmin', 'HomeSectionAdmin'), ('JobTypeAdmin', 'JobTypeAdmin'), ('LanguageAdmin', 'LanguageAdmin'), ('LocationAdmin', 'LocationAdmin'), ('LoginAdmin', 'LoginAdmin'), ('PositionAdmin', 'PositionAdmin'), ('RegionAdmin', 'RegionAdmin'), ('RegionAliasAdmin', 'RegionAliasAdmin'), ('RoomAdmin', 'RoomAdmin'), ('RoomTypeAdmin', 'RoomTypeAdmin'), ('ServiceAdmin', 'ServiceAdmin'), ('ServiceExtraAdmin', 'ServiceExtraAdmin'), ('ServiceTypeAdmin', 'ServiceTypeAdmin'), ('StructureAdmin', 'StructureAdmin'), ('TabletAdmin', 'TabletAdmin'), ('TimestampAdmin', 'TimestampAdmin'), ('TimestampDirectionAdmin', 'TimestampDirectionAdmin')], max_length=255, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='adminexportcsvmap',
            name='order',
            field=models.PositiveIntegerField(verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='adminexportcsvmap',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='adminlistdisplay',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='adminlistdisplay',
            name='field',
            field=models.CharField(max_length=255, verbose_name='field'),
        ),
        migrations.AlterField(
            model_name='adminlistdisplay',
            name='model',
            field=models.CharField(choices=[('ActivityAdmin', 'ActivityAdmin'), ('ActivityInLinesAdmin', 'ActivityInLinesAdmin'), ('ActivityRoomAdmin', 'ActivityRoomAdmin'), ('AdminExportCSVMapAdmin', 'AdminExportCSVMapAdmin'), ('AdminListDisplayAdmin', 'AdminListDisplayAdmin'), ('AdminListDisplayLinkAdmin', 'AdminListDisplayLinkAdmin'), ('AdminListFilterAdmin', 'AdminListFilterAdmin'), ('AdminOptionAdmin', 'AdminOptionAdmin'), ('AdminSearchableAdmin', 'AdminSearchableAdmin'), ('ApiCommandAdmin', 'ApiCommandAdmin'), ('ApiCommandTypeAdmin', 'ApiCommandTypeAdmin'), ('ApiContextTypeAdmin', 'ApiContextTypeAdmin'), ('ApiLogAdmin', 'ApiLogAdmin'), ('BedTypeAdmin', 'BedTypeAdmin'), ('BrandAdmin', 'BrandAdmin'), ('BuildingAdmin', 'BuildingAdmin'), ('CompanyAdmin', 'CompanyAdmin'), ('ContinentAdmin', 'ContinentAdmin'), ('ContractAdmin', 'ContractAdmin'), ('ContractTypeAdmin', 'ContractTypeAdmin'), ('CountryAdmin', 'CountryAdmin'), ('EmployeeAdmin', 'EmployeeAdmin'), ('EquipmentAdmin', 'EquipmentAdmin'), ('EquipmentTypeAdmin', 'EquipmentTypeAdmin'), ('HomeSectionAdmin', 'HomeSectionAdmin'), ('JobTypeAdmin', 'JobTypeAdmin'), ('LanguageAdmin', 'LanguageAdmin'), ('LocationAdmin', 'LocationAdmin'), ('LoginAdmin', 'LoginAdmin'), ('PositionAdmin', 'PositionAdmin'), ('RegionAdmin', 'RegionAdmin'), ('RegionAliasAdmin', 'RegionAliasAdmin'), ('RoomAdmin', 'RoomAdmin'), ('RoomTypeAdmin', 'RoomTypeAdmin'), ('ServiceAdmin', 'ServiceAdmin'), ('ServiceExtraAdmin', 'ServiceExtraAdmin'), ('ServiceTypeAdmin', 'ServiceTypeAdmin'), ('StructureAdmin', 'StructureAdmin'), ('TabletAdmin', 'TabletAdmin'), ('TimestampAdmin', 'TimestampAdmin'), ('TimestampDirectionAdmin', 'TimestampDirectionAdmin')], max_length=255, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='adminlistdisplay',
            name='order',
            field=models.PositiveIntegerField(verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='adminlistdisplaylink',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='adminlistdisplaylink',
            name='field',
            field=models.CharField(max_length=255, verbose_name='field'),
        ),
        migrations.AlterField(
            model_name='adminlistdisplaylink',
            name='model',
            field=models.CharField(choices=[('ActivityAdmin', 'ActivityAdmin'), ('ActivityInLinesAdmin', 'ActivityInLinesAdmin'), ('ActivityRoomAdmin', 'ActivityRoomAdmin'), ('AdminExportCSVMapAdmin', 'AdminExportCSVMapAdmin'), ('AdminListDisplayAdmin', 'AdminListDisplayAdmin'), ('AdminListDisplayLinkAdmin', 'AdminListDisplayLinkAdmin'), ('AdminListFilterAdmin', 'AdminListFilterAdmin'), ('AdminOptionAdmin', 'AdminOptionAdmin'), ('AdminSearchableAdmin', 'AdminSearchableAdmin'), ('ApiCommandAdmin', 'ApiCommandAdmin'), ('ApiCommandTypeAdmin', 'ApiCommandTypeAdmin'), ('ApiContextTypeAdmin', 'ApiContextTypeAdmin'), ('ApiLogAdmin', 'ApiLogAdmin'), ('BedTypeAdmin', 'BedTypeAdmin'), ('BrandAdmin', 'BrandAdmin'), ('BuildingAdmin', 'BuildingAdmin'), ('CompanyAdmin', 'CompanyAdmin'), ('ContinentAdmin', 'ContinentAdmin'), ('ContractAdmin', 'ContractAdmin'), ('ContractTypeAdmin', 'ContractTypeAdmin'), ('CountryAdmin', 'CountryAdmin'), ('EmployeeAdmin', 'EmployeeAdmin'), ('EquipmentAdmin', 'EquipmentAdmin'), ('EquipmentTypeAdmin', 'EquipmentTypeAdmin'), ('HomeSectionAdmin', 'HomeSectionAdmin'), ('JobTypeAdmin', 'JobTypeAdmin'), ('LanguageAdmin', 'LanguageAdmin'), ('LocationAdmin', 'LocationAdmin'), ('LoginAdmin', 'LoginAdmin'), ('PositionAdmin', 'PositionAdmin'), ('RegionAdmin', 'RegionAdmin'), ('RegionAliasAdmin', 'RegionAliasAdmin'), ('RoomAdmin', 'RoomAdmin'), ('RoomTypeAdmin', 'RoomTypeAdmin'), ('ServiceAdmin', 'ServiceAdmin'), ('ServiceExtraAdmin', 'ServiceExtraAdmin'), ('ServiceTypeAdmin', 'ServiceTypeAdmin'), ('StructureAdmin', 'StructureAdmin'), ('TabletAdmin', 'TabletAdmin'), ('TimestampAdmin', 'TimestampAdmin'), ('TimestampDirectionAdmin', 'TimestampDirectionAdmin')], max_length=255, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='adminlistdisplaylink',
            name='order',
            field=models.PositiveIntegerField(verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='adminlistfilter',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='adminlistfilter',
            name='field',
            field=models.CharField(max_length=255, verbose_name='field'),
        ),
        migrations.AlterField(
            model_name='adminlistfilter',
            name='model',
            field=models.CharField(choices=[('ActivityAdmin', 'ActivityAdmin'), ('ActivityInLinesAdmin', 'ActivityInLinesAdmin'), ('ActivityRoomAdmin', 'ActivityRoomAdmin'), ('AdminExportCSVMapAdmin', 'AdminExportCSVMapAdmin'), ('AdminListDisplayAdmin', 'AdminListDisplayAdmin'), ('AdminListDisplayLinkAdmin', 'AdminListDisplayLinkAdmin'), ('AdminListFilterAdmin', 'AdminListFilterAdmin'), ('AdminOptionAdmin', 'AdminOptionAdmin'), ('AdminSearchableAdmin', 'AdminSearchableAdmin'), ('ApiCommandAdmin', 'ApiCommandAdmin'), ('ApiCommandTypeAdmin', 'ApiCommandTypeAdmin'), ('ApiContextTypeAdmin', 'ApiContextTypeAdmin'), ('ApiLogAdmin', 'ApiLogAdmin'), ('BedTypeAdmin', 'BedTypeAdmin'), ('BrandAdmin', 'BrandAdmin'), ('BuildingAdmin', 'BuildingAdmin'), ('CompanyAdmin', 'CompanyAdmin'), ('ContinentAdmin', 'ContinentAdmin'), ('ContractAdmin', 'ContractAdmin'), ('ContractTypeAdmin', 'ContractTypeAdmin'), ('CountryAdmin', 'CountryAdmin'), ('EmployeeAdmin', 'EmployeeAdmin'), ('EquipmentAdmin', 'EquipmentAdmin'), ('EquipmentTypeAdmin', 'EquipmentTypeAdmin'), ('HomeSectionAdmin', 'HomeSectionAdmin'), ('JobTypeAdmin', 'JobTypeAdmin'), ('LanguageAdmin', 'LanguageAdmin'), ('LocationAdmin', 'LocationAdmin'), ('LoginAdmin', 'LoginAdmin'), ('PositionAdmin', 'PositionAdmin'), ('RegionAdmin', 'RegionAdmin'), ('RegionAliasAdmin', 'RegionAliasAdmin'), ('RoomAdmin', 'RoomAdmin'), ('RoomTypeAdmin', 'RoomTypeAdmin'), ('ServiceAdmin', 'ServiceAdmin'), ('ServiceExtraAdmin', 'ServiceExtraAdmin'), ('ServiceTypeAdmin', 'ServiceTypeAdmin'), ('StructureAdmin', 'StructureAdmin'), ('TabletAdmin', 'TabletAdmin'), ('TimestampAdmin', 'TimestampAdmin'), ('TimestampDirectionAdmin', 'TimestampDirectionAdmin')], max_length=255, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='adminlistfilter',
            name='order',
            field=models.PositiveIntegerField(verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='adminoption',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='adminoption',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='enabled'),
        ),
        migrations.AlterField(
            model_name='adminoption',
            name='group',
            field=models.CharField(default='main', max_length=255, verbose_name='group'),
        ),
        migrations.AlterField(
            model_name='adminoption',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='adminoption',
            name='section',
            field=models.CharField(max_length=255, verbose_name='section'),
        ),
        migrations.AlterField(
            model_name='adminoption',
            name='value',
            field=models.TextField(blank=True, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='adminsearchable',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='adminsearchable',
            name='field',
            field=models.CharField(max_length=255, verbose_name='field'),
        ),
        migrations.AlterField(
            model_name='adminsearchable',
            name='model',
            field=models.CharField(choices=[('ActivityAdmin', 'ActivityAdmin'), ('ActivityInLinesAdmin', 'ActivityInLinesAdmin'), ('ActivityRoomAdmin', 'ActivityRoomAdmin'), ('AdminExportCSVMapAdmin', 'AdminExportCSVMapAdmin'), ('AdminListDisplayAdmin', 'AdminListDisplayAdmin'), ('AdminListDisplayLinkAdmin', 'AdminListDisplayLinkAdmin'), ('AdminListFilterAdmin', 'AdminListFilterAdmin'), ('AdminOptionAdmin', 'AdminOptionAdmin'), ('AdminSearchableAdmin', 'AdminSearchableAdmin'), ('ApiCommandAdmin', 'ApiCommandAdmin'), ('ApiCommandTypeAdmin', 'ApiCommandTypeAdmin'), ('ApiContextTypeAdmin', 'ApiContextTypeAdmin'), ('ApiLogAdmin', 'ApiLogAdmin'), ('BedTypeAdmin', 'BedTypeAdmin'), ('BrandAdmin', 'BrandAdmin'), ('BuildingAdmin', 'BuildingAdmin'), ('CompanyAdmin', 'CompanyAdmin'), ('ContinentAdmin', 'ContinentAdmin'), ('ContractAdmin', 'ContractAdmin'), ('ContractTypeAdmin', 'ContractTypeAdmin'), ('CountryAdmin', 'CountryAdmin'), ('EmployeeAdmin', 'EmployeeAdmin'), ('EquipmentAdmin', 'EquipmentAdmin'), ('EquipmentTypeAdmin', 'EquipmentTypeAdmin'), ('HomeSectionAdmin', 'HomeSectionAdmin'), ('JobTypeAdmin', 'JobTypeAdmin'), ('LanguageAdmin', 'LanguageAdmin'), ('LocationAdmin', 'LocationAdmin'), ('LoginAdmin', 'LoginAdmin'), ('PositionAdmin', 'PositionAdmin'), ('RegionAdmin', 'RegionAdmin'), ('RegionAliasAdmin', 'RegionAliasAdmin'), ('RoomAdmin', 'RoomAdmin'), ('RoomTypeAdmin', 'RoomTypeAdmin'), ('ServiceAdmin', 'ServiceAdmin'), ('ServiceExtraAdmin', 'ServiceExtraAdmin'), ('ServiceTypeAdmin', 'ServiceTypeAdmin'), ('StructureAdmin', 'StructureAdmin'), ('TabletAdmin', 'TabletAdmin'), ('TimestampAdmin', 'TimestampAdmin'), ('TimestampDirectionAdmin', 'TimestampDirectionAdmin')], max_length=255, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='adminsearchable',
            name='ref_field',
            field=models.CharField(max_length=255, verbose_name='referenced field'),
        ),
        migrations.AlterField(
            model_name='adminsearchable',
            name='ref_model',
            field=models.CharField(choices=[('ActivityAdmin', 'ActivityAdmin'), ('ActivityInLinesAdmin', 'ActivityInLinesAdmin'), ('ActivityRoomAdmin', 'ActivityRoomAdmin'), ('AdminExportCSVMapAdmin', 'AdminExportCSVMapAdmin'), ('AdminListDisplayAdmin', 'AdminListDisplayAdmin'), ('AdminListDisplayLinkAdmin', 'AdminListDisplayLinkAdmin'), ('AdminListFilterAdmin', 'AdminListFilterAdmin'), ('AdminOptionAdmin', 'AdminOptionAdmin'), ('AdminSearchableAdmin', 'AdminSearchableAdmin'), ('ApiCommandAdmin', 'ApiCommandAdmin'), ('ApiCommandTypeAdmin', 'ApiCommandTypeAdmin'), ('ApiContextTypeAdmin', 'ApiContextTypeAdmin'), ('ApiLogAdmin', 'ApiLogAdmin'), ('BedTypeAdmin', 'BedTypeAdmin'), ('BrandAdmin', 'BrandAdmin'), ('BuildingAdmin', 'BuildingAdmin'), ('CompanyAdmin', 'CompanyAdmin'), ('ContinentAdmin', 'ContinentAdmin'), ('ContractAdmin', 'ContractAdmin'), ('ContractTypeAdmin', 'ContractTypeAdmin'), ('CountryAdmin', 'CountryAdmin'), ('EmployeeAdmin', 'EmployeeAdmin'), ('EquipmentAdmin', 'EquipmentAdmin'), ('EquipmentTypeAdmin', 'EquipmentTypeAdmin'), ('HomeSectionAdmin', 'HomeSectionAdmin'), ('JobTypeAdmin', 'JobTypeAdmin'), ('LanguageAdmin', 'LanguageAdmin'), ('LocationAdmin', 'LocationAdmin'), ('LoginAdmin', 'LoginAdmin'), ('PositionAdmin', 'PositionAdmin'), ('RegionAdmin', 'RegionAdmin'), ('RegionAliasAdmin', 'RegionAliasAdmin'), ('RoomAdmin', 'RoomAdmin'), ('RoomTypeAdmin', 'RoomTypeAdmin'), ('ServiceAdmin', 'ServiceAdmin'), ('ServiceExtraAdmin', 'ServiceExtraAdmin'), ('ServiceTypeAdmin', 'ServiceTypeAdmin'), ('StructureAdmin', 'StructureAdmin'), ('TabletAdmin', 'TabletAdmin'), ('TimestampAdmin', 'TimestampAdmin'), ('TimestampDirectionAdmin', 'TimestampDirectionAdmin')], max_length=255, verbose_name='referenced model'),
        ),
        migrations.AlterField(
            model_name='adminsearchable',
            name='use_select2',
            field=models.BooleanField(verbose_name='use select 2'),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='admin_login_required',
            field=models.BooleanField(default=False, verbose_name='admin login required'),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='header_order',
            field=models.IntegerField(verbose_name='header order'),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='header_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='header title'),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='home_image',
            field=models.CharField(blank=True, max_length=255, verbose_name='home image'),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='home_order',
            field=models.IntegerField(verbose_name='home order'),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='home_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='home title'),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='link',
            field=models.CharField(blank=True, max_length=255, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='login_required',
            field=models.BooleanField(default=False, verbose_name='login required'),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='name'),
        ),
    ]
