# Generated by Django 2.1.3 on 2018-12-03 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0037_remove_employee_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('genre', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('birth_date', models.DateField()),
                ('address', models.TextField(blank=True)),
                ('postal_code', models.CharField(blank=True, max_length=15)),
                ('phone1', models.CharField(blank=True, max_length=255)),
                ('phone2', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('vat_number', models.CharField(blank=True, max_length=255)),
                ('tax_code', models.CharField(blank=True, max_length=255)),
                ('permit', models.CharField(blank=True, max_length=255)),
                ('permit_date', models.DateField(blank=True, default=None, null=True)),
                ('permit_expiration', models.DateField(blank=True, default=None, null=True)),
                ('photo', models.ImageField(blank=True, default='standard:genre_unknown_1', null=True, upload_to='hotels/images/employees/')),
                ('birth_location', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='work_employee_birth_location', to='locations.Location')),
                ('location', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='work_employee_location', to='locations.Location')),
                ('permit_location', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='work_employee_permit_location', to='locations.Location')),
            ],
            options={
                'db_table': 'work_employees',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('first_name', 'last_name', 'tax_code')},
        ),
        migrations.RunSQL(
            "INSERT INTO work_employees "
            "  (first_name, last_name, description, birth_date, address, "
            "   phone1, phone2, email, vat_number, tax_code, photo, genre, "
            "   birth_location_id, location_id, permit, permit_date, "
            "   permit_expiration, permit_location_id, postal_code)"
            "SELECT first_name, last_name, description, birth_date, address, "
            "   phone1, phone2, email, vat_number, tax_code, photo, genre, "
            "   birth_location_id, location_id, permit, permit_date, "
            "   permit_expiration, permit_location_id, postal_code "
            "FROM hotels_employees",
        ),
    ]
