# Generated by Django 2.1.4 on 2018-12-09 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_auto_20181203_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birth_location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='employee_birth_location', to='locations.Location'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='employee_location', to='locations.Location'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='permit_location',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.Location'),
        ),
    ]
