# Generated by Django 2.1.4 on 2018-12-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_deletion_protect'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'work_jobtype',
                'ordering': ['name'],
            },
        ),
    ]
