# Generated by Django 2.1.4 on 2018-12-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_jobtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('daily_hours', models.PositiveIntegerField()),
                ('weekly_hours', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'work_contracttype',
                'ordering': ['name'],
            },
        ),
    ]
