# Generated by Django 2.1.4 on 2018-12-09 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timestamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('<', 'Enter'), ('>', 'Exit')], max_length=1)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.TextField(blank=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work.Contract')),
            ],
            options={
                'db_table': 'work_timestamps',
                'ordering': ['contract', 'date', 'time'],
            },
        ),
    ]
