# Generated by Django 2.1.3 on 2018-12-13 22:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0039_deletion_protect'),
        ('work', '0008_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='guid',
            field=models.UUIDField(blank=True, default=uuid.uuid4),
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('guid',), ('company', 'employee', 'roll_number'), ('company', 'employee', 'start_date', 'end_date')},
        ),
    ]
