# Generated by Django 2.1.4 on 2018-12-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_contract_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
