# Generated by Django 2.1.4 on 2018-12-30 22:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0039_deletion_protect'),
        ('work', '0011_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('status', models.BooleanField(default=True)),
                ('guid', models.UUIDField(blank=True, default=uuid.uuid4)),
                ('buildings', models.ManyToManyField(blank=True, db_table='work_tablet_buildings', to='hotels.Building')),
            ],
            options={
                'db_table': 'work_tablet',
                'ordering': ['id'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='tablet',
            unique_together={('guid',)},
        ),
    ]
