# Generated by Django 2.1.4 on 2019-01-05 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0012_tablet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work.Contract')),
                ('timestamps', models.ManyToManyField(blank=True, db_table='work_activity_timestamps', to='work.Timestamp')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'db_table': 'work_activities',
                'ordering': ['contract', 'date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('contract', 'date')},
        ),
    ]
