# Generated by Django 2.1.4 on 2019-01-06 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0041_roomservice'),
        ('work', '0013_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work.Activity')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotels.Room')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotels.Service')),
            ],
            options={
                'verbose_name_plural': 'Activity Rooms',
                'db_table': 'work_activities_rooms',
                'ordering': ['activity', 'room', 'service'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='activityroom',
            unique_together={('activity', 'room', 'service')},
        ),
    ]
