# Generated by Django 2.1.4 on 2019-01-06 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0041_roomservice'),
        ('work', '0015_activityinlinesproxy'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='buildings',
            field=models.ManyToManyField(blank=True, db_table='work_contract_buildings', to='hotels.Building'),
        ),
    ]
