# Generated by Django 2.1.4 on 2019-01-06 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0016_contract_buildings'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttype',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='work.ContractType'),
        ),
        migrations.AlterField(
            model_name='contracttype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
