# Generated by Django 2.1.5 on 2019-01-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0021_activityroom_service_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='tax_code',
            field=models.CharField(max_length=255),
        ),
    ]
