# Generated by Django 2.1.5 on 2019-01-19 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0024_timestamp_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestamp',
            name='direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work.TimestampDirection'),
        ),
        migrations.RunSQL(sql=[('UPDATE work_timestamps SET direction_id=('
                                '  SELECT id FROM work_timestamp_directions WHERE type_enter=1 limit 1'
                                ') WHERE direction_id=%s', ['<', ])],
                          reverse_sql=[('UPDATE work_timestamps SET direction_id=%s '
                                        'WHERE direction_id=('
                                        '  SELECT id FROM work_timestamp_directions WHERE type_enter=1 limit 1'
                                        ')', ['<', ])]
        ),
        migrations.RunSQL(sql=[('UPDATE work_timestamps SET direction_id=('
                                '  SELECT id FROM work_timestamp_directions WHERE type_exit=1 limit 1'
                                ') WHERE direction_id=%s', ['>', ])],
                          reverse_sql=[('UPDATE work_timestamps SET direction_id=%s '
                                        'WHERE direction_id=('
                                        '  SELECT id FROM work_timestamp_directions WHERE type_exit=1 limit 1'
                                        ')', ['>', ])]
        ),
        migrations.AlterUniqueTogether(
            name='timestamp',
            unique_together={('contract', 'direction', 'date', 'time')},
        ),
    ]
