# Generated by Django 2.1.5 on 2019-01-20 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0025_timestamp_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='timestamps',
        ),
    ]
