# Generated by Django 2.1.5 on 2019-01-20 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0026_remove_activity_timestamps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-date', 'contract__employee'], 'verbose_name_plural': 'Activities'},
        ),
    ]
