# Generated by Django 2.1.5 on 2019-01-28 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0027_activity_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestampdirection',
            name='short_code',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
