# Generated by Django 2.1.5 on 2019-01-31 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0028_timestampdirection_short_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='status',
            new_name='enabled',
        ),
    ]
