# Generated by Django 2.1.5 on 2019-03-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0029_contract_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='genre',
            new_name='gender',
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, default='standard:gender_unknown_1', null=True, upload_to='hotels/images/employees/'),
        ),
        migrations.RunSQL(
            "UPDATE work_employees "
            "SET photo = REPLACE(photo, 'standard:genre_', 'standard:gender_')"
        ),
    ]
