# Generated by Django 2.1.5 on 2019-05-14 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0034_work_tablet_setting'),
        ('work', '0030_rename_genre_to_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabletSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.AdminSection')),
                ('tablets', models.ManyToManyField(blank=True, to='work.Tablet')),
            ],
            options={
                'db_table': 'work_tablet_settings',
                'ordering': ['configuration'],
            },
        ),
    ]
