# Generated by Django 2.2.2 on 2019-06-23 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0031_tabletsetting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TabletSetting',
        ),
    ]
