# Generated by Django 2.2.3 on 2019-07-18 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0032_delete_tabletsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='contract',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='work.Contract'),
            preserve_default=False,
        ),
    ]
