# Generated by Django 2.2.3 on 2019-07-18 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0033_login_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='employee',
        ),
    ]
