# Generated by Django 2.2.9 on 2020-01-24 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0035_translations'),
    ]

    operations = [
        migrations.RunSQL('DROP VIEW IF EXISTS work_activities_full_view'),
        migrations.AddField(
            model_name='employee',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='blacklist'),
        ),
        migrations.RunSQL("""
            CREATE VIEW work_activities_full_view AS
            SELECT 
              'work_activities_rooms' as table1,
              work_activities_rooms.*,
              'work_activities' as table2,
              work_activities.*,
              'hotels_rooms' as table3,
              hotels_rooms.*,
              'hotels_buildings' as table4,
              hotels_buildings.*,
              'hotels_structures' as table5,
              hotels_structures.*,
              'work_contracts' as table6,
              work_contracts.*,
              'work_employees' as table7,
              work_employees.*
            FROM work_activities_rooms
            INNER JOIN work_activities
               ON work_activities.id = work_activities_rooms.activity_id
            INNER JOIN hotels_rooms
               ON hotels_rooms.id = work_activities_rooms.room_id
            INNER JOIN hotels_buildings
               ON hotels_buildings.id = hotels_rooms.building_id
            INNER JOIN hotels_structures
               ON hotels_structures.id = hotels_buildings.structure_id
            INNER JOIN work_contracts
              ON work_contracts.id = work_activities.contract_id
            INNER JOIN work_employees
               ON work_employees.id = work_contracts.employee_id
        """),
    ]
