# Generated by Django 2.1.3 on 2018-11-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
