# Generated by Django 2.1.3 on 2018-11-11 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_roomtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Building')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Floor')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.RoomType')),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
    ]
