# Generated by Django 2.1.3 on 2018-11-11 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_room'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('building', 'name')},
        ),
    ]
