# Generated by Django 2.1.3 on 2018-11-13 22:00

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('hotels', '0012_pagesection'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='building',
            table='hotels_buildings',
        ),
        migrations.AlterModelTable(
            name='company',
            table='hotels_companies',
        ),
        migrations.AlterModelTable(
            name='floor',
            table='hotels_floors',
        ),
        migrations.AlterModelTable(
            name='hotel',
            table='hotels_hotels',
        ),
        migrations.AlterModelTable(
            name='pagesection',
            table='hotels_page_sections',
        ),
        migrations.AlterModelTable(
            name='roletype',
            table='hotels_roletypes',
        ),
        migrations.AlterModelTable(
            name='room',
            table='hotels_rooms',
        ),
        migrations.AlterModelTable(
            name='roomtype',
            table='hotels_roomtypes',
        ),
    ]
