# Generated by Django 2.1.3 on 2018-11-18 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0013_auto_20181113_2300'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
    ]
