# Generated by Django 2.1.3 on 2018-11-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0014_auto_20181118_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tax_code',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='vat_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
