# Generated by Django 2.1.3 on 2018-11-24 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0015_auto_20181124_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'hotels_brands',
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='brand',
            field=models.ForeignKey(default='UNKNOWN', on_delete=django.db.models.deletion.CASCADE, to='hotels.Brand'),
        ),
    ]
