# Generated by Django 2.1.3 on 2018-11-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0016_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='postal_code',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
