# Generated by Django 2.1.3 on 2018-11-24 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0019_auto_20181124_2130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['hotel', 'name']},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='pagesection',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='roletype',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['building', 'name']},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'ordering': ['name']},
        ),
    ]
