# Generated by Django 2.1.3 on 2018-11-24 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0022_auto_20181125_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedType',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True,
                                          serialize=False)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'hotels_bed_types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='bed_type',
            field=models.ForeignKey(
                default='UNKNOWN',
                on_delete=django.db.models.deletion.CASCADE,
                to='hotels.BedType'),
        ),
    ]
