# Generated by Django 2.1.3 on 2018-11-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0024_room_phone1'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='seats_additional',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='seats_base',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
