# Generated by Django 2.1.3 on 2018-11-25 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0025_room_seats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageSection',
        ),
    ]
