# Generated by Django 2.1.3 on 2018-11-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0026_delete_pagesection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('birth_date', models.DateField()),
                ('address', models.TextField(blank=True)),
                ('phone1', models.CharField(blank=True, max_length=255)),
                ('phone2', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('vat_number', models.CharField(blank=True, max_length=255)),
                ('tax_code', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'hotels_employees',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('first_name', 'last_name', 'tax_code')},
        ),
    ]
