# Generated by Django 2.1.3 on 2018-12-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0029_building_name_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='genre',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], default='unknown', max_length=10),
        ),
    ]
