# Generated by Django 2.1.3 on 2018-12-02 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0030_employee_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, default='standard:genre_unknown_1', null=True, upload_to='hotels/images/employees/'),
        ),
    ]
