# Generated by Django 2.1.3 on 2018-12-02 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0031_employee_photo_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='code',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
