# Generated by Django 2.1.3 on 2018-12-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0032_employee_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
