# Generated by Django 2.1.3 on 2018-12-02 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0013_auto_20181119_0150'),
        ('hotels', '0033_company_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('phone1', models.CharField(blank=True, max_length=255)),
                ('phone2', models.CharField(blank=True, max_length=255)),
                ('fax', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('brand', models.ForeignKey(default='UNKNOWN', on_delete=django.db.models.deletion.CASCADE, to='hotels.Brand')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Company')),
                ('location', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='locations.Location')),
            ],
            options={
                'db_table': 'hotels_structures',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['hotel', 'structure', 'name']},
        ),
        migrations.RunSQL(
            "INSERT INTO hotels_structures "
            "  (name, description, address, location_id, phone1, phone2, fax, email, brand_id, company_id)"
            "SELECT name, description, address, location_id, phone1, phone2, fax, email, brand_id, company_id "
            "FROM hotels_hotels",
        ),
        migrations.AddField(
            model_name='building',
            name='structure',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hotels.Structure'),
            preserve_default=False,
        ),
        migrations.RunSQL(
            "UPDATE hotels_buildings "
            "SET structure_id=hotel_id",
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['structure', 'name']},
        ),
        migrations.RemoveField(
            model_name='building',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='company',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='location',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
