# Generated by Django 2.1.3 on 2018-12-02 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0034_structure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoleType',
        ),
    ]
