# Generated by Django 2.1.3 on 2018-12-02 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0014_auto_20181202_2041'),
        ('hotels', '0035_delete_roletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birth_location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='employee_birth_location', to='locations.Location'),
        ),
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
        migrations.AddField(
            model_name='employee',
            name='permit',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='permit_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='permit_expiration',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='permit_location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='employee_permit_location', to='locations.Location'),
        ),
        migrations.AddField(
            model_name='employee',
            name='postal_code',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
