# Generated by Django 2.1.3 on 2018-12-02 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0036_auto_20181202_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='code',
        ),
    ]
