# Generated by Django 2.1.3 on 2018-12-03 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0037_remove_employee_code'),
        ('work', '0001_employee'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='birth_location',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='location',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='permit_location',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
