# Generated by Django 2.1.4 on 2018-12-09 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0038_delete_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='locations.Location'),
        ),
        migrations.AlterField(
            model_name='building',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotels.Structure'),
        ),
        migrations.AlterField(
            model_name='room',
            name='bed_type',
            field=models.ForeignKey(default='UNKNOWN', on_delete=django.db.models.deletion.PROTECT, to='hotels.BedType'),
        ),
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotels.Building'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotels.RoomType'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='brand',
            field=models.ForeignKey(default='UNKNOWN', on_delete=django.db.models.deletion.PROTECT, to='hotels.Brand'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotels.Company'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='locations.Location'),
        ),
    ]
