# Generated by Django 2.1.4 on 2019-01-05 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0040_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='hotels.Service')),
            ],
            options={
                'db_table': 'hotels_room_services',
                'ordering': ['service'],
            },
        ),
    ]
