# Generated by Django 2.1.4 on 2019-01-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0047_auto_20190109_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomservice',
            name='service',
        ),
        migrations.AddField(
            model_name='service',
            name='room_service',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='RoomService',
        ),
    ]
