# Generated by Django 2.1.4 on 2019-01-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0048_removed_roomservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='extra_service',
            field=models.BooleanField(default=False),
        ),
    ]
