# Generated by Django 2.1.5 on 2019-01-15 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0049_service_extra_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('structure', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='hotels.Structure')),
            ],
            options={
                'db_table': 'hotels_structure_equipments',
                'ordering': ['structure', 'name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='equipment',
            unique_together={('structure', 'name')},
        ),
    ]
