# Generated by Django 2.1.5 on 2019-01-16 00:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0050_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=11, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('service', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='hotels.Service')),
                ('structure', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='hotels.Structure')),
            ],
            options={
                'verbose_name_plural': 'Services Extras',
                'db_table': 'hotels_services_extra',
                'ordering': ['structure', 'service'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='serviceextra',
            unique_together={('structure', 'service')},
        ),
    ]
