# Generated by Django 2.1.5 on 2019-01-31 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0051_service_extra'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='equipment',
            table='hotels_equipments',
        ),
    ]
