# Generated by Django 2.1.5 on 2019-02-08 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0055_equipment_name_non_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField()),
                ('show_in_reports', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Services Types',
                'db_table': 'hotels_services_types',
                'ordering': ['order', 'name'],
            },
        ),
    ]
