# Generated by Django 2.2.3 on 2019-07-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0058_service_show_in_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='extras',
            field=models.BooleanField(default=False),
        ),
    ]
