# Generated by Django 2.2.5 on 2019-09-03 17:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0059_building_extras'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bedtype',
            options={'ordering': ['name'], 'verbose_name': 'Bed type', 'verbose_name_plural': 'Bed types'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': 'Brand', 'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['structure', 'name'], 'verbose_name': 'Building', 'verbose_name_plural': 'Buildings'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='equipment',
            options={'ordering': ['structure', 'name'], 'verbose_name': 'Equipment', 'verbose_name_plural': 'Equipments'},
        ),
        migrations.AlterModelOptions(
            name='equipmenttype',
            options={'ordering': ['name'], 'verbose_name': 'Equipment type', 'verbose_name_plural': 'Equipment types'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['building', 'name'], 'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'ordering': ['name'], 'verbose_name': 'Room type', 'verbose_name_plural': 'Room types'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='serviceextra',
            options={'ordering': ['structure', 'service'], 'verbose_name': 'Service extra', 'verbose_name_plural': 'Service extras'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Service type', 'verbose_name_plural': 'Service types'},
        ),
        migrations.AlterModelOptions(
            name='structure',
            options={'ordering': ['name'], 'verbose_name': 'Structure', 'verbose_name_plural': 'Structures'},
        ),
        migrations.AlterField(
            model_name='bedtype',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='bedtype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.TextField(blank=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='building',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='building',
            name='email',
            field=models.CharField(blank=True, max_length=255, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='building',
            name='extras',
            field=models.BooleanField(default=False, verbose_name='extras'),
        ),
        migrations.AlterField(
            model_name='building',
            name='fax',
            field=models.CharField(blank=True, max_length=255, verbose_name='fax'),
        ),
        migrations.AlterField(
            model_name='building',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='locations.Location', verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='building',
            name='phone1',
            field=models.CharField(blank=True, max_length=255, verbose_name='phone 1'),
        ),
        migrations.AlterField(
            model_name='building',
            name='phone2',
            field=models.CharField(blank=True, max_length=255, verbose_name='phone 2'),
        ),
        migrations.AlterField(
            model_name='building',
            name='postal_code',
            field=models.CharField(blank=True, max_length=15, verbose_name='postal code'),
        ),
        migrations.AlterField(
            model_name='building',
            name='structure',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='hotels.Structure', verbose_name='structure'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.CharField(blank=True, max_length=255, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fax',
            field=models.CharField(blank=True, max_length=255, verbose_name='fax'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.CharField(blank=True, max_length=255, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone1',
            field=models.CharField(blank=True, max_length=255, verbose_name='phone 1'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone2',
            field=models.CharField(blank=True, max_length=255, verbose_name='phone 2'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_code',
            field=models.CharField(blank=True, max_length=255, verbose_name='tax code'),
        ),
        migrations.AlterField(
            model_name='company',
            name='vat_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='VAT number'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='hotels.EquipmentType', verbose_name='equipment type'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='structure',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='hotels.Structure', verbose_name='structure'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='room',
            name='bed_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='hotels.BedType', verbose_name='bed type'),
        ),
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotels.Building', verbose_name='building'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='room',
            name='phone1',
            field=models.CharField(blank=True, max_length=255, verbose_name='phone 1'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotels.RoomType', verbose_name='room type'),
        ),
        migrations.AlterField(
            model_name='room',
            name='seats_additional',
            field=models.PositiveIntegerField(default=0, verbose_name='seats additional'),
        ),
        migrations.AlterField(
            model_name='room',
            name='seats_base',
            field=models.PositiveIntegerField(default=1, verbose_name='seats base'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='extra_service',
            field=models.BooleanField(default=False, verbose_name='extra service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='room_service',
            field=models.BooleanField(default=False, verbose_name='room service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='hotels.ServiceType', verbose_name='service type'),
        ),
        migrations.AlterField(
            model_name='service',
            name='show_in_app',
            field=models.BooleanField(default=False, verbose_name='show in app'),
        ),
        migrations.AlterField(
            model_name='serviceextra',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=11, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='serviceextra',
            name='service',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='hotels.Service', verbose_name='service'),
        ),
        migrations.AlterField(
            model_name='serviceextra',
            name='structure',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='hotels.Structure', verbose_name='structure'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='order',
            field=models.PositiveIntegerField(verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='show_in_reports',
            field=models.BooleanField(default=True, verbose_name='show in report'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='address',
            field=models.TextField(blank=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='brand',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='hotels.Brand', verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='hotels.Company', verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='email',
            field=models.CharField(blank=True, max_length=255, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='fax',
            field=models.CharField(blank=True, max_length=255, verbose_name='fax'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='locations.Location', verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='phone1',
            field=models.CharField(blank=True, max_length=255, verbose_name='phone 1'),
        ),
        migrations.AlterField(
            model_name='structure',
            name='phone2',
            field=models.CharField(blank=True, max_length=255, verbose_name='phone 2'),
        ),
    ]
