# Generated by Django 2.2.10 on 2020-03-01 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0060_translations'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('equipment_type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='hotels.EquipmentType', verbose_name='equipment type')),
            ],
            options={
                'verbose_name': 'Equipment item',
                'verbose_name_plural': 'Equipment items',
                'db_table': 'hotels_equipments_item',
                'ordering': ['name'],
            },
        ),
        migrations.RunSQL("INSERT INTO hotels_equipments_item "
                          "(id, name, description, equipment_type_id) "
                          "VALUES(0, 'UNKNOWN', 'UNKNOWN', 0)",
                          migrations.RunSQL.noop),
        migrations.RunSQL("INSERT INTO hotels_equipments_item "
                          "(name, description, equipment_type_id) "
                          "SELECT DISTINCT "
                          "  name, "
                          "  '', "
                          "  equipment_type_id "
                          "FROM hotels_equipments "
                          "WHERE name NOT IN ( "
                          "  SELECT "
                          "    name "
                          "  FROM hotels_equipments_item "
                          ") "
                          "  AND id != 0",
                          migrations.RunSQL.noop)
    ]
