# Generated by Django 2.2.10 on 2020-03-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0061_equipment_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('sign', models.CharField(choices=[('+', '+'), ('-', '-')], max_length=1, verbose_name='sign for quantity')),
            ],
            options={
                'verbose_name': 'Equipment direction',
                'verbose_name_plural': 'Equipment directions',
                'db_table': 'hotels_equipment_directions',
                'ordering': ['name'],
            },
        ),
    ]
