# Generated by Django 2.2.10 on 2020-03-02 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0062_equipment_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantity')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('direction', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='hotels.EquipmentDirection', verbose_name='direction')),
                ('item', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='hotels.EquipmentItem', verbose_name='item')),
                ('structure', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='hotels.Structure', verbose_name='structure')),
            ],
            options={
                'verbose_name': 'Equipment detail',
                'verbose_name_plural': 'Equipment details',
                'db_table': 'hotels_equipment_details',
                'ordering': ['date', 'structure'],
            },
        ),
    ]
