# Generated by Django 2.1.3 on 2018-11-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True,
                                          serialize=False)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'locations_continents',
            },
        ),
    ]
