# Generated by Django 2.1.3 on 2018-11-13 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'locations_positions',
            },
        ),
    ]
