# Generated by Django 2.1.3 on 2018-11-18 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20181114_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='languages',
            field=models.ManyToManyField(to='locations.Language'),
        ),
    ]
