# Generated by Django 2.1.3 on 2018-11-18 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_auto_20181118_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Region')),
            ],
            options={
                'db_table': 'locations_locations',
                'ordering': ['name'],
            },
        ),
    ]
