# Generated by Django 2.1.3 on 2018-11-19 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_region_aliases'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location'
        ),
    ]
