# Generated by Django 2.1.3 on 2018-12-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0013_auto_20181119_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='aliases',
            field=models.ManyToManyField(blank=True, db_table='locations_region_aliases', to='locations.RegionAlias'),
        ),
    ]
