# Generated by Django 2.1.4 on 2018-12-09 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0015_auto_20181203_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.Continent'),
        ),
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.Region'),
        ),
        migrations.AlterField(
            model_name='region',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.Country'),
        ),
        migrations.AlterField(
            model_name='region',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.Position'),
        ),
        migrations.AlterField(
            model_name='regionalias',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.Country'),
        ),
    ]
