# Generated by Django 2.2.5 on 2019-09-03 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0016_deletion_protect'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='continent',
            options={'ordering': ['name'], 'verbose_name': 'Continent', 'verbose_name_plural': 'Continents'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name'], 'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['name'], 'verbose_name': 'Position', 'verbose_name_plural': 'Positions'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name'], 'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterModelOptions(
            name='regionalias',
            options={'ordering': ['name'], 'verbose_name': 'Region alias', 'verbose_name_plural': 'Region aliases'},
        ),
        migrations.AlterField(
            model_name='continent',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='continent',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='country',
            name='capital',
            field=models.CharField(blank=True, max_length=255, verbose_name='capital'),
        ),
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.Continent', verbose_name='continent'),
        ),
        migrations.AlterField(
            model_name='country',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='country',
            name='languages',
            field=models.ManyToManyField(to='locations.Language', verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='language',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='province',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='province'),
        ),
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.Region', verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='region',
            name='aliases',
            field=models.ManyToManyField(blank=True, db_table='locations_region_aliases', to='locations.RegionAlias', verbose_name='aliases'),
        ),
        migrations.AlterField(
            model_name='region',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.Country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='region',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='region',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.Position', verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='regionalias',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locations.Country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='regionalias',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='regionalias',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
